#!/bin/bash
# Martin Häggström 231226

VERSION=$1

check_go_version_semantics() {

  #https://go.dev/doc/modules/version-numbers

  local VERSION=$1

  echo $VERSION | grep -qE '^v[0-9]\.[0-9]\.[0-9](|-(alpha|beta)\.?[0-9]?)$'
  [ $? -eq 0 ] || { echo "WRONG_VERSION"; exit 1; }
}

set_version() {

  local VERSION=$1

  # Does the tag exist?
  EXIST=$(git tag --list ''${VERSION}'')

  if [ -z "$EXIST" ]
  then
    git commit -am "Update $VERSION"
    git tag "$VERSION"
	
    #pushes to branch.*.remote and defaults to origin
	  git push origin "$VERSION"
	  git push
  fi

}

check_go_version_semantics $VERSION
set_version $VERSION
